var countries = [
  {"Chequered Flag":"🏁"},
  {"Triangular Flag":"🚩"},
  {"Crossed Flags":"🎌"},
  {"Black Flag":"🏴"},
  {"White Flag":"🏳️"},
  {"Rainbow Flag":"🏳️‍🌈"},
  {"Transgender Flag":"🏳️‍⚧️"},
  {"Pirate Flag":"🏴‍☠️"},
  {"Ascension Island":"🇦🇨"},
  {"Andorra":"🇦🇩"},
  {"United Arab Emirates":"🇦🇪"},
  {"Afghanistan":"🇦🇫"},
  {"Antigua & Barbuda":"🇦🇬"},
  {"Antigua And Barbuda":"🇦🇬"},
  {"Anguilla":"🇦🇮"},
  {"Albania":"🇦🇱"},
  {"Armenia":"🇦🇲"},
  {"Angola":"🇦🇴"},
  {"Antarctica":"🇦🇶"},
  {"Argentina":"🇦🇷"},
  {"American Samoa":"🇦🇸"},
  {"Austria":"🇦🇹"},
  {"Australia":"🇦🇺"},
  {"Aruba":"🇦🇼"},
  {"Åland Islands":"🇦🇽"},
  {"Azerbaijan":"🇦🇿"},
  {"Bosnia & Herzegovina":"🇧🇦"},
  {"Bosnia And Herzegovina":"🇧🇦"},
  {"Barbados":"🇧🇧"},
  {"Bangladesh":"🇧🇩"},
  {"Belgium":"🇧🇪"},
  {"Burkina Faso":"🇧🇫"},
  {"Bulgaria":"🇧🇬"},
  {"Bahrain":"🇧🇭"},
  {"Burundi":"🇧🇮"},
  {"Benin":"🇧🇯"},
  {"St. Barthelemy":"🇧🇱"},
  {"Bermuda":"🇧🇲"},
  {"Brunei":"🇧🇳"},
  {"Bolivia":"🇧🇴"},
  {"Bolivia, Plurinational State Of":"🇧🇴"},
  {"Caribbean Netherlands":"🇧🇶"},
  {"Brazil":"🇧🇷"},
  {"Bahamas":"🇧🇸"},
  {"Bhutan":"🇧🇹"},
  {"Bouvet Island":"🇧🇻"},
  {"Botswana":"🇧🇼"},
  {"Belarus":"🇧🇾"},
  {"Belize":"🇧🇿"},
  {"Canada":"🇨🇦"},
  {"Cocos (Keeling) Islands":"🇨🇨"},
  {"Congo, The Democratic Republic Of The":"🇨🇩"},
  {"Democratic Republic of the Congo":"🇨🇩"},
  {"Central African Republic":"🇨🇫"},
  {"Congo":"🇨🇬"},
  {"Switzerland":"🇨🇭"},
  {"Cote d'Ivoire":"🇨🇮"},
  {"Cote d'ivoire":"🇨🇮"},
  {"Cote D'ivoire":"🇨🇮"},
  {"CÔte D'ivoire":"🇨🇮"},
  {"Cook Islands":"🇨🇰"},
  {"Chile":"🇨🇱"},
  {"Cameroon":"🇨🇲"},
  {"China":"🇨🇳"},
  {"Colombia":"🇨🇴"},
  {"Clipperton Island":"🇨🇵"},
  {"Costa Rica":"🇨🇷"},
  {"Cuba":"🇨🇺"},
  {"Cape Verde":"🇨🇻"},
  {"Curaçao":"🇨🇼"},
  {"Christmas Island":"🇨🇽"},
  {"Cyprus":"🇨🇾"},
  {"Czechia":"🇨🇿"},
  {"Czech Republic":"🇨🇿"},
  {"Germany":"🇩🇪"},
  {"Diego Garcia":"🇩🇬"},
  {"Djibouti":"🇩🇯"},
  {"Denmark":"🇩🇰"},
  {"Dominica":"🇩🇲"},
  {"Dominican Republic":"🇩🇴"},
  {"Algeria":"🇩🇿"},
  {"Ceuta & Melilla":"🇩🇿"},
  {"Ecuador":"🇪🇨"},
  {"Estonia":"🇪🇪"},
  {"Egypt":"🇪🇬"},
  {"Western Sahara":"🇪🇭"},
  {"Eritrea":"🇪🇷"},
  {"Spain":"🇪🇸"},
  {"Ethiopia":"🇪🇹"},
  {"European Union":"🇪🇺"},
  {"EU":"🇪🇺"},
  {"E.U.":"🇪🇺"},
  {"Finland":"🇫🇮"},
  {"Fiji":"🇫🇯"},
  {"Falkland Islands":"🇫🇰"},
  {"Micronesia":"🇫🇲"},
  {"Faroe Islands":"🇫🇴"},
  {"France":"🇫🇷"},
  {"Gabon":"🇬🇦"},
  {"United Kingdom":"🇬🇧"},
  {"UK":"🇬🇧"},
  {"U.K.":"🇬🇧"},
  {"Grenada":"🇬🇩"},
  {"Georgia":"🇬🇪"},
  {"French Guiana":"🇬🇫"},
  {"Guernsey":"🇬🇬"},
  {"Ghana":"🇬🇭"},
  {"Gibraltar":"🇬🇮"},
  {"Greenland":"🇬🇱"},
  {"Gambia":"🇬🇲"},
  {"Guinea":"🇬🇳"},
  {"Guadeloupe":"🇬🇵"},
  {"Equatorial Guinea":"🇬🇶"},
  {"Greece":"🇬🇷"},
  {"South Georgia & South Sandwich Islands":"🇬🇸"},
  {"Guatemala":"🇬🇹"},
  {"Guam":"🇬🇺"},
  {"Guinea-Bissau":"🇬🇼"},
  {"Guinea-bissau":"🇬🇼"},
  {"Guyana":"🇬🇾"},
  {"Hong Kong SAR China":"🇭🇰"},
  {"Heard & McDonald Islands":"🇭🇲"},
  {"Honduras":"🇭🇳"},
  {"Croatia":"🇭🇷"},
  {"Haiti":"🇭🇹"},
  {"Hungary":"🇭🇺"},
  {"Canary Islands":"🇮🇨"},
  {"Indonesia":"🇮🇩"},
  {"Ireland":"🇮🇪"},
  {"Israel":"🇮🇱"},
  {"Isle of Man":"🇮🇲"},
  {"India":"🇮🇳"},
  {"British Indian Ocean Territory":"🇮🇴"},
  {"Iraq":"🇮🇶"},
  {"Iran":"🇮🇷"},
  {"Iceland":"🇮🇸"},
  {"Italy":"🇮🇹"},
  {"Jersey":"🇯🇪"},
  {"Jamaica":"🇯🇲"},
  {"Jordan":"🇯🇴"},
  {"Japan":"🇯🇵"},
  {"Kenya":"🇰🇪"},
  {"Kyrgyzstan":"🇰🇬"},
  {"Cambodia":"🇰🇭"},
  {"Kiribati":"🇰🇮"},
  {"Comoros":"🇰🇲"},
  {"St. Kitts & Nevis":"🇰🇳"},
  {"Saint Kitts And Nevis":"🇰🇳"},
  {"North Korea":"🇰🇵"},
  {"Korea, Democratic People's Republic Of":"🇰🇵"},
  {"South Korea":"🇰🇷"},
  {"Korea, Republic Of":"🇰🇷"},
  {"Kuwait":"🇰🇼"},
  {"Cayman Islands":"🇰🇾"},
  {"Kazakhstan":"🇰🇿"},
  {"Laos":"🇱🇦"},
  {"Lao People's Democratic Republic":"🇱🇦"},
  {"Lebanon":"🇱🇧"},
  {"St. Lucia":"🇱🇨"},
  {"Liechtenstein":"🇱🇮"},
  {"Sri Lanka":"🇱🇰"},
  {"Liberia":"🇱🇷"},
  {"Libya":"🇱🇾"},
  {"Lesotho":"🇱🇸"},
  {"Lithuania":"🇱🇹"},
  {"Luxembourg":"🇱🇺"},
  {"Latvia":"🇱🇻"},
  {"Morocco":"🇲🇦"},
  {"Monaco":"🇲🇨"},
  {"Moldova":"🇲🇩"},
  {"Montenegro":"🇲🇪"},
  {"St. Martin":"🇲🇫"},
  {"Madagascar":"🇲🇬"},
  {"Marshall Islands":"🇲🇭"},
  {"North Macedonia":"🇲🇰"},
  {"Macedonia, The Former Yugoslav Republic Of":"🇲🇰"},
  {"Mali":"🇲🇱"},
  {"Myanmar":"🇲🇲"},
  {"Burma":"🇲🇲"},
  {"Mongolia":"🇲🇳"},
  {"Macao Sar China":"🇲🇴"},
  {"Northern Mariana Islands":"🇲🇵"},
  {"Martinique":"🇲🇶"},
  {"Mauritania":"🇲🇷"},
  {"Montserrat":"🇲🇸"},
  {"Malta":"🇲🇹"},
  {"Mauritius":"🇲🇺"},
  {"Maldives":"🇲🇻"},
  {"Malawi":"🇲🇼"},
  {"Mexico":"🇲🇽"},
  {"Malaysia":"🇲🇾"},
  {"Mozambique":"🇲🇿"},
  {"Namibia":"🇳🇦"},
  {"New Caledonia":"🇳🇨"},
  {"Niger":"🇳🇪"},
  {"Norfolk Island":"🇳🇫"},
  {"Nigeria":"🇳🇫"},
  {"Nicaragua":"🇳🇮"},
  {"Netherlands":"🇳🇱"},
  {"Norway":"🇳🇴"},
  {"Nepal":"🇳🇵"},
  {"Nauru":"🇳🇷"},
  {"Niue":"🇳🇺"},
  {"New Zealand":"🇳🇿"},
  {"Oman":"🇴🇲"},
  {"Panama":"🇵🇦"},
  {"Peru":"🇵🇪"},
  {"French Polynesia":"🇵🇫"},
  {"Papua New Guinea":"🇵🇬"},
  {"Philippines":"🇵🇭"},
  {"Pakistan":"🇵🇰"},
  {"Poland":"🇵🇱"},
  {"St. Pierre & Miquelon":"🇵🇲"},
  {"St. Pierre":"🇵🇲"},
  {"Miquelon":"🇵🇲"},
  {"Pitcairn Islands":"🇵🇳"},
  {"Puerto Rico":"🇵🇷"},
  {"Palestinian Territories":"🇵🇸"},
  {"Portugal":"🇵🇹"},
  {"Palau":"🇵🇼"},
  {"Paraguay":"🇵🇾"},
  {"Qatar":"🇶🇦"},
  {"Reunion":"🇷🇪"},
  {"Romania":"🇷🇴"},
  {"Serbia":"🇷🇸"},
  {"Russia":"🇷🇺"},
  {"Russian Federation":"🇷🇺"},
  {"Rwanda":"🇷🇼"},
  {"Saudi Arabia":"🇸🇦"},
  {"Solomon Islands":"🇸🇧"},
  {"Seychelles":"🇸🇨"},
  {"Sudan":"🇸🇩"},
  {"Sweden":"🇸🇪"},
  {"Singapore":"🇸🇬"},
  {"St. Helena":"🇸🇭"},
  {"Slovenia":"🇸🇮"},
  {"Svalbard & Jan Mayen":"🇸🇯"},
  {"Svalbard":"🇸🇯"},
  {"Jan Mayen":"🇸🇯"},
  {"Slovakia":"🇸🇰"},
  {"Sierra Leone":"🇸🇱"},
  {"San Marino":"🇸🇲"},
  {"Senegal":"🇸🇳"},
  {"Somalia":"🇸🇴"},
  {"Suriname":"🇸🇷"},
  {"South Sudan":"🇸🇸"},
  {"São Tomé & Príncipe":"🇸🇹"},
  {"Sao Tome & Principe":"🇸🇹"},
  {"Sao Tome":"🇸🇹"},
  {"Principe":"🇸🇹"},
  {"El Salvador":"🇸🇻"},
  {"Sint Maarten":"🇸🇽"},
  {"Syria":"🇸🇾"},
  {"Syrian Arab Republic":"🇸🇾"},
  {"Eswatini":"🇸🇿"},
  {"Tristan Da Cunha":"🇹🇦"},
  {"Turks & Caicos Islands":"🇹🇨"},
  {"Turks":"🇹🇨"},
  {"Turks Islands":"🇹🇨"},
  {"Caicos Islands":"🇹🇨"},
  {"Chad":"🇹🇩"},
  {"French Southern Territories":"🇹🇫"},
  {"Togo":"🇹🇬"},
  {"Thailand":"🇹🇭"},
  {"Tajikistan":"🇹🇯"},
  {"Tokelau":"🇹🇰"},
  {"Timor-Leste":"🇹🇱"},
  {"Turkmenistan":"🇹🇲"},
  {"Tunisia":"🇹🇳"},
  {"Tonga":"🇹🇴"},
  {"Turkey":"🇹🇷"},
  {"Trinidad & Tobago":"🇹🇹"},
  {"Trinidad And Tobago":"🇹🇹"},
  {"Tuvalu":"🇹🇻"},
  {"Taiwan":"🇹🇼"},
  {"Tanzania":"🇹🇿"},
  {"Tanzania, United Republic Of":"🇹🇿"},
  {"Ukraine":"🇺🇦"},
  {"Uganda":"🇺🇬"},
  {"U.S. Outlying Islands":"🇺🇲"},
  {"United Nations":"🇺🇳"},
  {"UN":"🇺🇳"},
  {"U.N.":"🇺🇳"},
  {"United States":"🇺🇸"},
  {"United States of America":"🇺🇸"},
  {"US":"🇺🇸"},
  {"U.S.":"🇺🇸"},
  {"USA":"🇺🇸"},
  {"U.S.A.":"🇺🇸"},
  {"Uruguay":"🇺🇾"},
  {"Uzbekistan":"🇺🇿"},
  {"Vatican City":"🇻🇦"},
  {"St. Vincent & Grenadines":"🇻🇨"},
  {"Venezuela":"🇻🇪"},
  {"Venezuela, Bolivarian Republic Of":"🇻🇪"},
  {"British Virgin Islands":"🇻🇬"},
  {"U.S. Virgin Islands":"🇻🇮"},
  {"Vietnam":"🇻🇳"},
  {"Viet Nam":"🇻🇳"},
  {"Vanuatu":"🇻🇺"},
  {"Wallis & Futuna":"🇼🇫"},
  {"Samoa":"🇼🇸"},
  {"Kosovo":"🇽🇰"},
  {"Yemen":"🇾🇪"},
  {"Mayotte":"🇾🇹"},
  {"South Africa":"🇿🇦"},
  {"Zambia":"🇿🇲"},
  {"Zimbabwe":"🇿🇼"},
  {"England":"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
  {"Scotland":"🏴󠁧󠁢󠁳󠁣󠁴󠁿"},
  {"Wales":"🏴󠁧󠁢󠁷󠁬󠁳󠁿"},
  {"Texas":"🏴󠁵󠁳󠁴󠁸󠁿"},
  {"Refugee Nation":"🏳‍🟧‍⬛‍🟧"}
]